services:
  backend:
    build: .
    container_name: backend
    depends_on:
      - redis
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--requirepass your_password_here --appendonly yes
    restart: always

  worker:
    build: .
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend
    command: python celery -A core worker --loglevel=info

  beat:
    build: .
    depends_on:
      - redis
      - worker
    command: python celery -A core beat -l info
    volumes:
      - ./core:/app

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: on-failure
    ports:
      # Change the number before : to the port the web interface should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '143:143'
      # Change the number before : to the port the POP3 server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '110:110'
    volumes:
      # This is where smtp4dev stores the database..
      - smtp4dev-data:/smtp4dev
    environment:
      #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
      - ServerOptions__HostName=smtp4dev

  locust:
    image: locustio/locust:latest
    container_name: locust
    depends_on:
      - backend
    working_dir: /mnt/locust
    volumes:
      - ./core:/mnt/locust
    ports:
      - "8089:8089"
    command: >
      -f /mnt/locust/locust/locustfile.py
      --host=http://backend:8000


volumes:
  smtp4dev-data:
  redis-data: