# Generated by Django 4.2.11 on 2026-07-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments_commentsreplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
