# Generated by Django 4.2.11 on 2026-07-29 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, default='blog/default.png', null=True, upload_to='blog/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='فقط فایل\u200cهای تصویری با فرمت JPG, JPEG, PNG مجاز هستند.')]),
        ),
    ]
