# Generated by Django 4.2.11 on 2026-07-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posts_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='commentsreplies',
            options={'ordering': ['created_date']},
        ),
    ]
